<a href="https://colab.research.google.com/github/adnan855570/Numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **What is numpy?**

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

# **Numpy Arrays Vs Python Sequences**

* NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

* The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

* A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.





## **Creating Numpy Arrays**

### np.array

In [221]:

import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


### type of data

In [222]:
print(type(a))

<class 'numpy.ndarray'>


### 2D and 3D array

In [223]:


b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [224]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


### dtype for datatype of numpy array

In [225]:


np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [226]:
np.array([1,2,3],dtype=bool) # every non-zero in python is treated as True

array([ True,  True,  True])

In [227]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

### np.arange

In [228]:


np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [229]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

### with reshape

In [230]:

np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### np.ones and np.zeros

In [231]:

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [232]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### np.random

In [233]:

np.random.random((3,4))

array([[0.87172953, 0.72681735, 0.49839132, 0.79849124],
       [0.92624617, 0.2528272 , 0.12982416, 0.65073623],
       [0.54880275, 0.61553129, 0.31985373, 0.64711994]])

### np.linspace

In [234]:

np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

### np.linspace

In [235]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# **Array Attributes**

In [236]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [237]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [238]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### ndim

In [239]:

a1.ndim

1

In [240]:
a2.ndim

2

In [241]:
a3.ndim

3

### shape

In [242]:

print(a1.shape)
a1

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [243]:
print(a2.shape)
a2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [244]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### size

In [245]:

print(a1.size)
a1

10


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [246]:
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [247]:
print(a3.size)
a3

8


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### itemsize

In [248]:

a1.itemsize

8

In [249]:
a2.itemsize

8

In [250]:
a3.itemsize

8

### dtype

In [251]:

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# **Changing Datatpye**

### astype

In [252]:

a1.astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

# **Array Operations**

In [253]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## **1. scalar operations**

### arthimetic

In [254]:


a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [255]:
a1 - 2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [256]:
a1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [257]:
a2 / 2

array([[ 6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5],
       [10. , 10.5, 11. , 11.5]])

### relations operations

In [258]:

a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [259]:
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [260]:
a2 > 25

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [261]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

## **2. Vector Operations**

### arthimetic

In [262]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [263]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [264]:
a1 - a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [265]:
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [266]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# **Array Functions**

In [267]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[96., 61., 10.],
       [96., 82., 15.],
       [38., 50., 53.]])

### max Function

In [268]:
np.max(a1)

np.float64(96.0)

### min Function

In [269]:
np.min(a1)

np.float64(10.0)

### sum Function

In [270]:
np.sum(a1)

np.float64(501.0)

### prod function

In [271]:
np.prod(a1)

np.float64(696316815360000.0)

### to find number in rows or columns

In [272]:
np.max(a1, axis=1)

array([96., 96., 53.])

In [273]:
np.max(a1, axis=0)

array([96., 82., 53.])

### mean

In [274]:
np.mean(a1)

np.float64(55.666666666666664)

### median

In [275]:
np.median(a1)

np.float64(53.0)

### std

In [276]:
np.std(a1)

np.float64(29.93697082575694)

### var

In [277]:
np.var(a1 , axis=1)

array([1246.88888889, 1249.55555556,   42.        ])

### Trigonometric Functions

In [278]:
np.sin(a1)

array([[ 0.98358775, -0.96611777, -0.54402111],
       [ 0.98358775,  0.31322878,  0.65028784],
       [ 0.29636858, -0.26237485,  0.39592515]])

### dot Product

In [279]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

print(a2)
print(a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [280]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

### log and exponents

In [281]:
np.log(a2)

/tmp/ipython-input-970536687.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a2)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [282]:
np.exp(a3)

array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

### round floot and ceil functions

In [283]:
np.round(np.random.random((2,3))*100)

array([[75., 78., 23.],
       [ 3., 75., 60.]])

In [284]:
np.floor(np.random.random((2,3))*100)

array([[71., 94., 96.],
       [66., 78., 43.]])

In [285]:
np.ceil(np.random.random((2,3))*100)

array([[63., 39., 75.],
       [81., 27., 37.]])

# **Indexing and Slicing**

In [286]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [287]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [288]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [289]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [290]:
a2[1,1]

np.int64(5)

In [291]:
a3[0,1,1]

np.int64(3)

In [292]:
a3[0,0,0]

np.int64(0)

In [293]:
a3[1,1,0]

np.int64(6)

# **Slicing**

In [294]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [295]:
a1[0:4]

array([0, 1, 2, 3])

In [296]:
a1[0:4:3]

array([0, 3])

In [297]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [298]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [299]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [300]:
a2[0,:]

array([0, 1, 2, 3])

In [301]:
a2[1::2,0::3]

array([[4, 7]])

In [302]:
a2[1,:2]

array([4, 5])

In [303]:
a2[:,1]

array([1, 5, 9])

In [304]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [305]:
a2[0:2,2:4]

array([[2, 3],
       [6, 7]])

In [306]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [307]:
a3= np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [308]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [309]:
a3[::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

In [310]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [311]:
a3[0,1]

array([3, 4, 5])

In [312]:
a3[1,:,1]

array([10, 13, 16])

In [313]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

# **Iterating**

In [314]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [315]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [316]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [317]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [318]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [319]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [320]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# **Reshaping**

### reshape function

In [344]:
a1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### transpose function

In [321]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [322]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### ravel function
### converts the array into 1d array

In [323]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [324]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [325]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# **Stacking**

## horizontal stacking

In [326]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [327]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [328]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [329]:
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [330]:
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

## vertical Stacking

In [331]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# **Splitting numpy Arrays**

In [332]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

## Horizontal Splitting

In [333]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [334]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [335]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

## Vertical Splitting

In [337]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [342]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]