<a href="https://colab.research.google.com/github/adnan855570/Numpy/blob/main/Practice_Numpyipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [58]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [59]:
v = np.zeros(10)
v[4] = 1

print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [60]:
# Ask user for input
a = int(input("Enter number of rows (a): "))
b = int(input("Enter number of columns (b): "))

# Generate random array of shape (a, b)
arr = np.random.rand(a, b)

# Print the array
print("\nGenerated Array:")
print(arr)

# Calculate and print average of the array
avg = np.mean(arr)
print("\nAverage of the array:", avg)


Enter number of rows (a): 2
Enter number of columns (b): 3

Generated Array:
[[0.64991492 0.48382874 0.13206234]
 [0.32783785 0.8425811  0.34697547]]

Average of the array: 0.46386673616138685


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [61]:
def border_array(a, b):
    arr = np.zeros((a, b), dtype=int)

    # Set borders to 1
    arr[0, :] = 1        # top row
    arr[-1, :] = 1       # bottom row
    arr[:, 0] = 1        # left column
    arr[:, -1] = 1       # right column

    return arr

# Example
print(border_array(4, 4))

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [62]:
a1 = np.linspace(0, 1, 12)[1:-1]
print(a1)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [63]:
I = np.eye(3, 4, dtype=int)
print(I)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [64]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [65]:
# Random coordinates (10,2) in range 1 to 100
coords = np.random.randint(1, 101, size=(10, 2))

# Given point
point = np.array([20, 30])

# Compute Euclidean distances
distances = np.sqrt(np.sum((coords - point) ** 2, axis=1)).astype(int)

print("Random Coordinates:\n", coords)
print("\nGiven Point:", point)
print("\nDistance Array (integer):\n", distances)

Random Coordinates:
 [[24 86]
 [94  8]
 [ 8 53]
 [66 33]
 [69 74]
 [48 19]
 [20 55]
 [51 21]
 [ 2 93]
 [21 63]]

Given Point: [20 30]

Distance Array (integer):
 [56 77 25 46 65 30 25 32 65 33]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [66]:
np.unravel_index(100, (6, 7, 8))

(np.int64(1), np.int64(5), np.int64(4))

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [67]:
# Read input
arr = np.array(input().split(), dtype=float)

# Reverse the array
rev_arr = arr[::-1]

print(rev_arr)

1
[1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [68]:
arr = np.array([1, 2])

def count_elements(arr):
    return arr.size
count_elements(arr)

2

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [69]:
x = np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098,  68.82830233, 91.52064278])
def softmax(x):
    # Validate input
    if not isinstance(x, np.ndarray):
        raise TypeError("Input must be a NumPy array")
    if x.ndim != 1:
        raise ValueError("Input must be a 1D NumPy array")

    # Numerical stability trick
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)
print(softmax(x))

[4.57181033e-26 1.16249922e-20 7.73872594e-05 2.60358426e-05
 1.39571531e-10 9.99896577e-01]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [70]:
a = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]])

b = np.array([[1, 1, 1, 1, 1],
              [1, 1, 1, 1, 1]])

def vertical_stack(*arrays):
    # Ensure at least one array is provided
    if len(arrays) == 0:
        raise ValueError("At least one NumPy array must be provided")

    # Validate all inputs are NumPy arrays
    for arr in arrays:
        if not isinstance(arr, np.ndarray):
            raise TypeError("All inputs must be NumPy arrays")

    # Perform vertical stacking
    return np.vstack(arrays)

print(vertical_stack(a, b))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [71]:
from datetime import datetime, timedelta

def date_array(start, end):
    # Type check
    if not isinstance(start, str) or not isinstance(end, str):
        raise TypeError("Both start and end must be strings")

    # Format check & parsing
    try:
        start_date = datetime.strptime(start, "%Y-%m-%d")
        end_date = datetime.strptime(end, "%Y-%m-%d")
    except ValueError:
        raise ValueError("Date format must be YYYY-MM-DD")

    # Same year check
    if start_date.year != end_date.year:
        raise ValueError("Dates must be from the same year")

    # Logical order check
    if start_date > end_date:
        raise ValueError("Start date must be before or equal to end date")

    # Generate date range
    num_days = (end_date - start_date).days + 1
    dates = [(start_date + timedelta(days=i)).strftime("%Y-%m-%d")
             for i in range(num_days)]

    return np.array(dates)
print(date_array(start='2020-09-15', end='2020-09-25'))


['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']


###`Q-14:` Subtract the mean of each row from a matrix.

In [72]:
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Subtract mean of each row
result = X - X.mean(axis=1, keepdims=True)

print(result)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [73]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Swap column 1 and column 2
arr[:, [0, 1]] = arr[:, [1, 0]]

print(arr)

[[2 1 3]
 [5 4 6]
 [8 7 9]]


###`Q-16:` Replace odd elements in arrays with -1.

In [74]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Replace odd elements with -1
arr[arr % 2 == 1] = -1

print(arr)

[-1  2 -1  4 -1  6 -1]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [75]:
a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])

result = np.maximum(a, b)
print(result)

[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [76]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[8269, 7685, 8682, 5650, 7279],
       [3393, 1090, 2175, 4990, 6583],
       [2577, 5761, 8873, 6379, 8700],
       [5218, 3741, 7165, 6464, 8062],
       [1241, 5424,  874, 3922, 2548],
       [3507, 3243, 9735, 7247,  974],
       [5208, 2633, 2613, 2116, 6559],
       [5217, 3029, 3693, 4225, 8654]])

In [77]:
alternate_cols = arr1[:, ::2]
print("Every alternate column:\n", alternate_cols)


Every alternate column:
 [[8269 8682 7279]
 [3393 2175 6583]
 [2577 8873 8700]
 [5218 7165 8062]
 [1241  874 2548]
 [3507 9735  974]
 [5208 2613 6559]
 [5217 3693 8654]]


In [78]:
xmin = arr1.min()
xmax = arr1.max()

normalized_arr = (arr1 - xmin) / (xmax - xmin)
print("Normalized array:\n", normalized_arr)


Normalized array:
 [[0.83455592 0.76864914 0.88116465 0.53899108 0.72283038]
 [0.28427943 0.02437648 0.14682316 0.46450739 0.64428394]
 [0.1921905  0.55151789 0.90271978 0.62126171 0.88319603]
 [0.49023812 0.32355265 0.70996502 0.63085431 0.81119512]
 [0.04141745 0.51348606 0.         0.34397923 0.18891773]
 [0.29714479 0.26735131 1.         0.71921905 0.01128541]
 [0.48910958 0.19851033 0.19625324 0.14016477 0.64157544]
 [0.49012527 0.24320054 0.31813565 0.37817402 0.87800474]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [81]:
def nth_largest(arr, n):
    # Validate input types
    if not isinstance(arr, np.ndarray):
        raise TypeError("arr must be a NumPy array")
    if arr.ndim != 1:
        raise ValueError("arr must be a 1D NumPy array")
    if not isinstance(n, int):
        raise TypeError("n must be an integer")
    if n <= 0 or n > len(arr):
        raise ValueError("n must satisfy 1 <= n <= len(arr)")

    # Get nth largest
    return np.sort(arr)[-n]

arr = np.array([12, 34, 40, 7, 1, 0])
n = 3

print(nth_largest(arr, n))


12


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [82]:
a = np.array([1, 2, 3])

part1 = np.repeat(a, len(a))
part2 = np.tile(a, len(a))

result = np.concatenate((part1, part2))
print(result)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
